### ISSUE TITLE
Configuration.cs points to localhost as BasePath for API

### ISSUE THREAD

**Issue by moto-geek** [adobe-sign/AdobeSignCSharpSDK#2]
### Expected Behaviour
Configuration.cs
Configuration BasePath to be point to Adobesign API Endpoint or use BaseURI
BasePath = "https://api.echosign.com/api/rest/v6" at least for baseURI;

OR after baseURI returned, global BasePath variable to use return Access [API point + API Ver.] for use with the rest of the class objects. 

### Actual Behaviour

Build as is, attempts to use localhost as EndPoint of API, gets 404 or 403 error
BasePath = "http://localhost/api/rest/v6"; ?

### Reproduce Scenario (including but not limited to)

Build and reference into a web application at dll in Bin. 

#### Steps to Reproduce

Create API call to baseURI

#### Platform and Version

ASP.NET Forms Project running .net  4.6.1

#### Sample Code that illustrates the problem

public Configuration()
        {
            UserAgent = "AdobeSign_CSharpSdk_1_0";
            BasePath = "http://localhost/api/rest/v6";
            DefaultHeader = new ConcurrentDictionary<string, string>();
            ApiKey = new ConcurrentDictionary<string, string>();
            ApiKeyPrefix = new ConcurrentDictionary<string, string>();

            // Setting Timeout has side effects (forces ApiClient creation).
            Timeout = 100000;
        }
#### Logs taken while reproducing problem

Error Message API Response 404 error not found

**Comment by moto-geek** [comment]
I'm going to close this issue as I'm abandoning this SDK. CreateAgreement is non functional. Sending paramters in Swagger at Adobesign test screens works and doing exactly same with SDK not return response. Thanks for providing this SDK, but just can't make it work.

**Comment by adobesignsdk** [comment]
@moto-geek  Use BasePath as [https://api.echosign.com/api/rest/v6](url) instead of [http://localhost/api/rest/v6](url).

Below is sample code snippet to create agreement

`var xApiUser = xApiUser_example;
                var xOnBehalfOfUser = xOnBehalfOfUser_example;
                var authorization = authorizationToken;
                var xApiUser = xApiUser_example;
                BaseUrisApi baseUriInstance = new BaseUrisApi("https://api.echosign.com/api/rest/v6");
                ApiResponse<BaseUriInfo> getbaseUriResponse = baseUriInstance.GetBaseUrisWithHttpInfo(accessToken);

                AgreementsApi agreementsInstance = new AgreementsApi(getbaseUriResponse.Data.ApiAccessPoint + "api/rest/v6");

                AgreementCreationInfo agreementCreation = new AgreementCreationInfo();
                IO.Swagger.model.agreements.FileInfo fileInfo = new IO.Swagger.model.agreements.FileInfo();
                fileInfo.TransientDocumentId = "transientDocumentId";

                List<IO.Swagger.model.agreements.FileInfo> fileInfos = new List<IO.Swagger.model.agreements.FileInfo>();
                fileInfos.Add(fileInfo);

                ParticipantSetInfo participantSetInfo = new ParticipantSetInfo();

                ParticipantSetMemberInfo participantSetMemberInfo = new ParticipantSetMemberInfo();
                participantSetMemberInfo.Email = "email";

                List<ParticipantSetMemberInfo> participantSetMemberInfosList = new List<ParticipantSetMemberInfo>();
                participantSetMemberInfosList.Add(participantSetMemberInfo);

                participantSetInfo.MemberInfos = participantSetMemberInfosList;
                participantSetInfo.Order = 1;
                participantSetInfo.Role = ParticipantSetInfo.RoleEnum.SIGNER;

                List<ParticipantSetInfo> participantSetInfos = new List<ParticipantSetInfo>();
                participantSetInfos.Add(participantSetInfo);

                agreementCreation.FileInfos = fileInfos;
                agreementCreation.Name = "agreementName";

                agreementCreation.ParticipantSetsInfo = participantSetInfos;
                agreementCreation.SignatureType = AgreementCreationInfo.SignatureTypeEnum.ESIGN;
                agreementCreation.State = AgreementCreationInfo.StateEnum.INPROCESS;

                ApiResponse<AgreementCreationResponse> agrCreationResponse = agreementsInstance.CreateAgreementWithHttpInfo(accessToken, agreementCreation, xApiUser, xOnBehalfOfUser);
`

**Comment by adobesignsdk** [comment]
@moto-geek  Use BasePath as [https://api.echosign.com/api/rest/v6](url) instead of [http://localhost/api/rest/v6](url).

Below is sample code snippet to create agreement 

`{









                var xApiUser = xApiUser_example;
                var xOnBehalfOfUser = xOnBehalfOfUser_example;
                var authorization = authorizationToken;
                var xApiUser = xApiUser_example;
                BaseUrisApi baseUriInstance = new BaseUrisApi("https://api.echosign.com/api/rest/v6");
                ApiResponse<BaseUriInfo> getbaseUriResponse = baseUriInstance.GetBaseUrisWithHttpInfo(accessToken);
                AgreementsApi agreementsInstance = new AgreementsApi(getbaseUriResponse.Data.ApiAccessPoint + "api/rest/v6");
           
                AgreementCreationInfo agreementCreation = new AgreementCreationInfo();
                IO.Swagger.model.agreements.FileInfo fileInfo = new IO.Swagger.model.agreements.FileInfo();
                fileInfo.TransientDocumentId = "transientDocumentId";

                List<IO.Swagger.model.agreements.FileInfo> fileInfos = new List<IO.Swagger.model.agreements.FileInfo>();
                fileInfos.Add(fileInfo);

                ParticipantSetInfo participantSetInfo = new ParticipantSetInfo();

                ParticipantSetMemberInfo participantSetMemberInfo = new ParticipantSetMemberInfo();
                participantSetMemberInfo.Email = "email";

                List<ParticipantSetMemberInfo> participantSetMemberInfosList = new List<ParticipantSetMemberInfo>();
                participantSetMemberInfosList.Add(participantSetMemberInfo);

                participantSetInfo.MemberInfos = participantSetMemberInfosList;
                participantSetInfo.Order = 1;
                participantSetInfo.Role = ParticipantSetInfo.RoleEnum.SIGNER;

                List<ParticipantSetInfo> participantSetInfos = new List<ParticipantSetInfo>();
                participantSetInfos.Add(participantSetInfo);

                agreementCreation.FileInfos = fileInfos;
                agreementCreation.Name = "agreementName";

                agreementCreation.ParticipantSetsInfo = participantSetInfos;
                agreementCreation.SignatureType = AgreementCreationInfo.SignatureTypeEnum.ESIGN;
                agreementCreation.State = AgreementCreationInfo.StateEnum.INPROCESS;

                ApiResponse<AgreementCreationResponse> agrCreationResponse = agreementsInstance.CreateAgreementWithHttpInfo(accessToken, agreementCreation, xApiUser, xOnBehalfOfUser);
           
        }`

**Comment by adobesignsdk** [comment]
@moto-geek have you got chance to try above example?
